### ISSUE TITLE
Driving Servos over the Barrel Connector

### ISSUE THREAD

**Issue by ansarid** [MXET/SCUTTLE#10]
I tried soldering the DC barrel power to the LiPo connector input which worked to still power the BeagleBone Blue when using only the DC barrel to supply power. When I connected some servos and ran `rc_test_servos -s 1.5` the BeagleBone shut off immediately after the command was run. I unpluged and then plugged the beaglebone back in the lights came back on but the beaglebone refused to boot. I tried the SD card in another BeagleBone and the SD still works fine.

Point is we need a different solution for powering the servos from the beaglebone using just the dc barrel plug.

**Comment by dmalawey** [comment]
The required step for full functionality is to use a small 2S lipo that will be continuously recharged by our battery plugged into barrel jack.

JK, Feb 21, 2019 in youtube comment:
"@David Malawey The power is coming from the MP2615 charger IC. The regulator/motor load doesn't act like a battery and the MP2615 doesn't seem to be designed to provide a steady voltage without a battery load. Instead, it is going to oscillate between thinking the battery is full and in need of a charge.﻿"
