### ISSUE TITLE
Share skeleton code for Speech-to-Text

### ISSUE THREAD

**Issue by dmalawey** [MXET/SCUTTLE#14]
Please include:

1. Libraries installed (or libraries referenced, which we already installed)
2. Links to the API or documentation
3. Commands or minimal code to get started
4. Description of hardware used to accomplish the task

**Comment by dmalawey** [comment]
[Trial adding JASPER to Beaglebone.docx](https://github.com/dmalawey/Scuttle/files/2950171/Trial.adding.JASPER.to.Beaglebone.docx)

**Comment by ansarid** [comment]
Google [Speech Recognition Library](https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst):
`sudo pip3 install SpeechRecognition`

[PyAudio](https://people.csail.mit.edu/hubert/pyaudio/docs/) required to get audio from the microphone. (We are using the microphone built-in to the webcam)
`sudo pip3 install pyaudio`

Make sure a webcam with a built-in microphone or a standalone microphone is connected when running this code.

Code:
```
#!/usr/bin/env python3

import speech_recognition as sr

# get audio from the microphone
r = sr.Recognizer()

while 1:

	with sr.Microphone() as source:

		print("Speak:")

		audio = r.listen(source)

		try:
			print("You said " + r.recognize_google(audio))
		except sr.UnknownValueError:
			print("Could not understand audio")
		except sr.RequestError as e:
			print("Could not request results; {0}".format(e))
```

This library is super buggy and probably does not work well enough to be useful to us.
**Further testing is required.**
