### ISSUE TITLE
Build NEMA 17 gantry assembly

### ISSUE THREAD

**Issue by dmalawey** [MXET/SCUTTLE#15]
[CAD models](https://grabcad.com/library/openbuilds-various-hardware-1) of similar design concept by OpenBuilds.

[Youtube video](https://www.youtube.com/watch?v=W2GxLMvkjQw) of mechanism operation style.

First few components in Solidworks CAD are uploaded on [grabCAD](https://grabcad.com/library/scuttle-linear-actuator-in-progress-1)

**Comment by ansarid** [comment]
Issues driving servos and steppers at the same time.

**Comment by ansarid** [comment]
Feature request by @jadonk on [](github.com/strawsondesign/librobotcontrol) for built in stepper control function.
[Issue #158](https://github.com/StrawsonDesign/librobotcontrol/issues/158#issue-429453060)
