### ISSUE TITLE
Cannot SSH via wifi or USB to Beaglebone

### ISSUE THREAD

**Issue by SantiagoGarza96** [MXET/SCUTTLE#18]
We were working with scuttle in Thom 101 and using the latest image scuttle_v1. When powered with the battery pack, the beaglebone network did not show up, and couldn't ssh via cloud9 or putty. While the beaglebone was powered via USB to a laptop and using putty to ssh to the address 192.168.7.2, a connection never occurred and would time out, same for cloud9.

**Comment by ansarid** [comment]
User says issue fixed itself
