### ISSUE TITLE
ADC initialization error?

### ISSUE THREAD

**Issue by mortiz139** [MXET/SCUTTLE#29]
I am currently just trying to run rc_test_servo. I am testing the code before I plug in a servo. Once I run the code below, this is the error I receive. 

```
debian@scuttle:/var/lib/cloud9$ rc_test_servos -c 1 -p 0.0
ERROR in rc_adc_init, failed to open iio adc interface
Failed to write to 'state.settings'. EROFS: read-only file system, open '/var/lib/cloud9/.c9/state.settings' .
```

**Comment by dmalawey** [comment]
This trial was repeated on a different beaglebone with the same SD card, and the code executes with no error, and servo runs properly.  Does this mean the blue has a problem?

**Comment by ansarid** [comment]
@mortiz139 try running it with sudo

**Comment by ansarid** [comment]
Inactive issue for what seems like a lack of knowledge instead of an issue. Closing.
