### ISSUE TITLE
Self_installer.sh does not complete

### ISSUE THREAD

**Issue by dmalawey** [MXET/SCUTTLE#33]
The self_intaller does not finish it's job of installing packages and many errors follow.  

An example of the output is shown in this gist:  [problems with self_installer](https://gist.github.com/dmalawey/548086df8b3069f73360ee25d0f626f2)

**Comment by dmalawey** [comment]
A resolution to this problem has been generated (with help from Ahmad B.)  We will reopen the issue if this fix is not successful for other users.

**Please note the fix:**
The self-installer includes a command for expanding the partition containing the image on the SD card, so there is room for additional installations of packages.  After this "growing" of the partition we need to reboot so the machine recognizes the larger partition space.  The original self_installer did not perform a reboot.

*The new self_installer has been modified to have two parts.  After the first part, a reboot is commanded.*

**Steps for the new process:**

- Reflash the SD card (REQUIRED)
- Reconnect to wifi using the tamulink_wpa process or using [this process](https://gist.github.com/dmalawey/e4be9f3b5beba8ed49868065935127b7) at home.
- Run the self_installer [part 1](https://github.com/MXET/SCUTTLE/blob/master/software/scripts/self_installer_part1.sh)
- After the machine reboots, reopen a terminal and run self_installer [part 2](https://github.com/MXET/SCUTTLE/blob/master/software/scripts/self_installer_part2.sh)

**Comment by ReinhardtTanner** [comment]
I was able to complete self installer part 1, however I keep losing connection in cloud9 during step 2.

This is being done on my network at home because TAMU won't even let me do self installer part 1 for some reason.
I'm getting a read only error on the TAMU network.

An image is attached displaying the error.
![issue](https://user-images.githubusercontent.com/54809567/64122083-38835480-cd66-11e9-961d-3fb9774e45d2.png)

**Comment by dmalawey** [comment]
@ReinhardtTanner, two things to check:

1) you flashed using the very top version on the beagleboard.org/latest webpage, correct?  The name is **Debian 9.5 2018-10-07 4GB SD IoT**

The version called "flasher" may cause a problem since it attempts to write to the Blue's memory directly and subsequently will boot from onboard memory, limited to 4gb.

2) Double check that you have an internet connection.  The first part of the self_installer will run even with no internet.  See the [cheat sheet](https://github.com/MXET/SCUTTLE/tree/master/software) for commands.

**Comment by ReinhardtTanner** [comment]
Let me redo the process so I can narrow down a single issue.

**Comment by ReinhardtTanner** [comment]
Just checked, looks like I used the version below it, the LXQT version. I
am currently downloading the correct file (IoT) and then I will re-flash.

On Mon, Sep 2, 2019 at 10:36 AM Michael Reinhardt <reinhardttanner@tamu.edu>
wrote:

> Let me redo the process so I can narrow down a single issue.
>
> On Mon, Sep 2, 2019 at 10:35 AM dmalawey <notifications@github.com> wrote:
>
>> @ReinhardtTanner
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ReinhardtTanner&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=MW1OwNrQZ_sVGyZb8m4MlDoVmuulu-A2y0G-YChFm_k&m=Uq0gFREEJVa2ea3LL4ggxi2PZE4TNr62csqpQLrPx0E&s=TePxmCwU73Qpi3vikdLH_tVmk_oU4H4_26FizCHPcTo&e=>,
>> you flashed using the very top version on the beagleboard.org/latest
>> webpage, correct? The name is *Debian 9.5 2018-10-07 4GB SD IoT*
>>
>> The version called "flasher" may cause a problem since it attempts to
>> write to the Blue's memory directly and subsequently will boot from onboard
>> memory, limited to 4gb.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MXET_SCUTTLE_issues_33-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DANCFHX6HN6IFEIDLHW7E4XDQHUXFRA5CNFSM4ISR5WTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5WD2OA-23issuecomment-2D527187256&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=MW1OwNrQZ_sVGyZb8m4MlDoVmuulu-A2y0G-YChFm_k&m=Uq0gFREEJVa2ea3LL4ggxi2PZE4TNr62csqpQLrPx0E&s=GIh2pSi-86MPIb7BQp602xgwxXsHbT4lz-Lm9nmUwT0&e=>,
>> or mute the thread
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANCFHXZZBASF7E2BCZU3S43QHUXFRANCNFSM4ISR5WTA&d=DwMCaQ&c=u6LDEWzohnDQ01ySGnxMzg&r=MW1OwNrQZ_sVGyZb8m4MlDoVmuulu-A2y0G-YChFm_k&m=Uq0gFREEJVa2ea3LL4ggxi2PZE4TNr62csqpQLrPx0E&s=cqv7nWsxl95YAbt4OV1L5CAHQaYMn2nr_aZNLDKOVA0&e=>
>> .
>>
> --
>
> *Michael T. Reinhardt*
> Junior in Multidisciplinary Engineering Technology - Mechatronics
>


-- 

*Michael T. Reinhardt*
Junior in Multidisciplinary Engineering Technology - Mechatronics

**Comment by ReinhardtTanner** [comment]
Hey David I reflashed the correct version from the BeagleBoard site, however I am still having the read only issue. I am currently on my home network. Below is the terminal text.

```
debian@beaglebone:/var/lib/cloud9$
debian@beaglebone:/var/lib/cloud9$ cd ~
debian@beaglebone:~$ sudo bash self_installer_part1.sh
sudo: unable to open /var/lib/sudo/ts/debian: Read-only file system
[sudo] password for debian:
debian@beaglebone:~$
```

**Comment by dmalawey** [comment]
I think the next step is to learn what's going on with the space on the drive.  Please run commands from this video and output info on your boot drive. 

https://youtu.be/SzzNJBzTZss

@ansarid  please add other useful troubleshooting questions to check on.

**Comment by ansarid** [comment]
@ReinhardtTanner At exactly which step in the lab does this issue arise or become apparent?

**Comment by ReinhardtTanner** [comment]
Ok so the issue was resolved. It seemed like it was a problem with the board as the WiFi and connection to the Beagle from computer frequently dropped upon attempted execution of the install files. The two install files installed flawlessly once a new board was obtained. Keep in mind the SD card remained unchanged with the previous flash version.
