### ISSUE TITLE
Internet connectivity issue for BeagleBone. Input/output error 

### ISSUE THREAD

**Issue by jessaggie** [MXET/SCUTTLE#34]
Any attempted at connecting to the internet results in an input/output error. This includes trying to use 
```
ping google.com
```
 as well as the 
```
connmanctl
```
```
debian@scuttle:~/basics$ connmanctl -h                                                     
bash: /usr/bin/connmanctl: Input/output error 
```

**Comment by ansarid** [comment]
@jessaggie Do all commands return the `Input/output error`, or just some commands?

**Comment by jessaggie** [comment]
All commands returned the input/output error.

**Comment by jessaggie** [comment]
We have resolved this issue, possibly by reflashing the board
