### ISSUE TITLE
Can't save a file and keep getting fail to write error

### ISSUE THREAD

**Issue by jessaggie** [MXET/SCUTTLE#39]
Logged on to cloud 9 and every time I try to save a file or a change, this error pops up. 

`Failed to write to 'L1_encoder.py'. EROFS: read-only file system, open '/home/debian/basics/L1_encoder.py' .`

**Comment by ansarid** [comment]
@jessaggie Have you tried rebooting your Beaglebone? Most of the time a reboot will solve the issue.

**Comment by jessaggie** [comment]
The reboot fixed it. Thank you
