### ISSUE TITLE
Create video on checking barrel plug voltage

### ISSUE THREAD

**Issue by dmalawey** [MXET/SCUTTLE#5]
We need a video to show the functions of rc_test within SSH.

Please include instructions for the fewest commands to check the barrel plug voltage, for safety.

Let's mention it can be run also in cloud9

If we need to include a libary (adafruit BBIO?)  then we need to mention it's required, even if it was already installed in self_installer.sh

**Comment by ansarid** [comment]
I can create a video showing both cloud9 and ssh. You should be able to measure from the adc out of the box.
