### ISSUE TITLE
Purge confusing lines from all python files

### ISSUE THREAD

**Issue by dmalawey** [MXET/SCUTTLE#53]
I'm requesting a script to be written to discover and remove this line before any git-pushes.

#!/usr/bin/python3

This is not code that I want to teach in the classroom.  It has been recurringly generated and does not serve a purpose.

**Comment by ansarid** [comment]
That's the python shebang. It's true it's really not needed for the classroom code.
Removed in commit 974b7f9c0fd6ad3c6b43e6f36e7e5ee726c2fbf2
