### ISSUE TITLE
Unable to track objects based off of RGB values on camera

### ISSUE THREAD

**Issue by connortolbert** [MXET/SCUTTLE#57]
Howdy, I am using a Pi 3B and running the L2_track_target.py script and cannot get it to properly track RGB color combinations. I am using the image dated 2021-05-07 and have tested a multitude of different RGB combinations. I even tried testing them in different orders because I thought maybe they needed to be inputted in a different manner. I would like to be able to utilize this script to find and track objects based on RGB values and utilize the distance from the center printed out to follow a colored line made from tape
![IMG-4972](https://user-images.githubusercontent.com/71449340/139490947-6d67decb-6484-4bb4-b532-fa03e2d99a73.jpeg)
.

**Comment by dmalawey** [comment]
Please tell us what hardware you're using, including the camera.

Please tell us the behavior you DO GET since you DON'T GET "properly tracking RGB"

Then, please tell your setup steps in enough detail so someone could repeat the issue.  @ansarid do you still have the link that explains how to clearly state a problem?

**Comment by connortolbert** [comment]
> Please tell us what hardware you're using, including the camera.

We are using the logitech c922 pro hd stream webcam and microsoft lifecam HD-3000 camera given in lab. 


> Please tell us the behavior you DO GET since you DON'T GET "properly tracking RGB"

It states "No target located" 

> Then, please tell your setup steps in enough detail so someone could repeat the issue. @ansarid do you still have the link that explains how to clearly state a problem?

I downloaded the L2_track_target.py script, added the variables shown above, and changed the pixel setup to 1920 x 1080 in L1_camera. Afterwards, I changed the get ratio function to divide by 1920 to get the correct values. Besides that all I did was change the variable being inserted to the function to test different colors in the L2_track_target.py script.
![65722874169--B6016182-E6FF-4FC9-91D1-EC1FD93808C2](https://user-images.githubusercontent.com/71449340/139492217-7097730e-fd3e-41cb-9d3d-83db6767a7c6.jpeg)

**Comment by dmalawey** [comment]
Thanks @connortolbert now we are getting somewhere.  I think it's best to validate that your camera is producing the stream of jpeg images, before it gets pulled into python.  We have not tested the combo of Pi + Logitech C922 before.  

Take a look at [this guide](https://scuttlerobot.org/uploads/SCUTTLE_Operation_Guide.pdf) in section 2.1, Milestone 1.  This manual is copyrighted and we are still adjusting it so don't distribute.

**Comment by connortolbert** [comment]
Okay, thanks for the help!
