### ISSUE TITLE
Support BLDC / Field Orientated Control?

### ISSUE THREAD

**Issue by samuk** [MXET/SCUTTLE#59]
Hi, nice project!

 Just starting a robot project on a much smaller footprint, some commonality with your project. Looking to use smaller motors than you, but could potentially add support for larger motors to the driver board we're developing if it's of interest. 

More here: https://cloud.transition-space.org/s/KyTnsYjs4GRkXjZ 

Not exactly an issue, but couldn't spot an email for you.

**Comment by dmalawey** [comment]
Thanks for finding us!  You can email me at dmalawey at g mail dot com.  Taking a peek at your document this looks pretty elegant.  I'll be happy to read more about it.
