### ISSUE TITLE
Latest Image uses MXET/scuttle - should use new Repo

### ISSUE THREAD

**Issue by dmalawey** [MXET/SCUTTLE#61]
![image](https://user-images.githubusercontent.com/42623372/147528217-fcb32966-86f8-4c02-b7e1-1434a8f0b38b.png)

Please create updated image that has the latest repo so we can git pull to update right after we flash and boot with the image.

**Comment by ansarid** [comment]
@dmalawey I didn't get a response from you regarding this [here](https://github.com/scuttlerobot/SCUTTLE/issues/60#issuecomment-1001722961). So I guess this means you want to have the SCUTTLE repo on the image, which means also fixing the remote repository location. I'll fix that.

> ~delete SCUTTLE directory on the Pi
> ~git clone scuttlerobot/SCUTTLE
> 
> Are you just asking to remove the current SCUTTLE folder and clone it again from the latest source?

_Originally posted by @ansarid in https://github.com/scuttlerobot/SCUTTLE/issues/60#issuecomment-1001722961_
