### ISSUE TITLE
Commands found in cheat sheet need clarification

### ISSUE THREAD

**Issue by dmalawey** [MXET/SCUTTLE#62]
2021.12 Fresh flash - ipconfig and ifconfig returns "Unknown command."

`/sbin/ifconfig -a` shows what used to show when I entered "ifconfig"

What to do?

**Comment by ansarid** [comment]
Please use `sudo ifconfig`.

`ipconfig` is a Windows command and is not valid in Linux.

**Comment by dmalawey** [comment]
> `ipconfig` is a Windows command and is not valid in Linux.

![image](https://user-images.githubusercontent.com/42623372/147530115-ffc66fab-add8-4ba6-bce7-c69b710e2b55.png)

orly?

**Comment by dmalawey** [comment]
Please see if you can review our long-standing linux notes for any other mistakes such as the missing sudo on the "iwconfig" entry.   Would appreciate it. 

https://github.com/scuttlerobot/SCUTTLE/edit/master/software/README.md

**Comment by ansarid** [comment]
> > `ipconfig` is a Windows command and is not valid in Linux.
> 
> ![image](https://user-images.githubusercontent.com/42623372/147530115-ffc66fab-add8-4ba6-bce7-c69b710e2b55.png)
> 
> orly?

Yes. IP is a newer tool that's not at all related to ipconfig.

**Comment by ansarid** [comment]
> Please see if you can review our long-standing linux notes for any other mistakes such as the missing sudo on the "iwconfig" entry. Would appreciate it.
> 
> https://github.com/scuttlerobot/SCUTTLE/edit/master/software/README.md

will do

**Comment by ansarid** [comment]
@dmalawey Or we could drop our cheatsheet(or a lot of the commands on the cheatsheet) for the [better resources that already exist.](https://www.raspberrypi.com/documentation/computers/using_linux.html)
