### ISSUE TITLE
SICK LiDAR Data Inconsistent

### ISSUE THREAD

**Issue by lbbettinger** [MXET/SCUTTLE#64]
Ranges of LiDAR Data points are coming in as 0 [distance angle]:
<img width="237" alt="Screen Shot 2022-04-06 at 4 10 53 PM" src="https://user-images.githubusercontent.com/71853645/162072859-18e5f7e0-60bb-4948-892a-75886402eb8a.png">
We were getting up to 10-15 0 values in a row earlier. This is while using a fully charged SCUTTLE battery pack. Using a bench-top power supply results in little to no errors.

Current (Temporary Wiring):
![IMG_1121](https://user-images.githubusercontent.com/71853645/162072717-15cd849e-5b20-485a-ba24-e8b5c91ec7b1.jpeg)
SICK LiDAR is connected to the motor controller's 12V terminals. These terminals are then connected to the battery pack. The Orange SICK LiDAR power cable is currently fairly long since wire routing is still undecided. I suspect the wiring is the issue.

**Comment by dmalawey** [comment]
OK here are some things you can check:

1. check the voltage of the battery.  the PIC has voltage/power meters that plug into anderson connectors.  Make sure in your trials the voltage is matched between battery and power supply
3.  check your surroundings - run your 2 trials with matching surroundings. (dont move the bot)  If the lidar strikes a reflective surface it won't get a value back.  Same if the distance is above 10m (see datasheet)
4. Please define "fairly long cable" - also I don't recognize this orange cable as we purchased a set of high-quality cables for all of the LIDARS in MXET 300 which you can probably borrow. 
5. Please define "little to no errors" - when you have errors what do they look like?
6. Please build a proper y-connector to split off your anderson power.  This configuration shown is not good practice.  We have videos for building splitters.

**Comment by lbbettinger** [comment]
Shortening the cable and using Anderson Powerpole connectors resolved inconsistencies with the LiDAR

**Comment by lbbettinger** [comment]
Shortening the cable and using Anderson Powerpole connectors resolved inconsistencies with the LiDAR
